version: "3.9"

services:
  backend:
    build: .
    env_file:
      - .env
    container_name: uniconnect-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - uniconnect_net

networks:
  uniconnect_net:
    external: true
