apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniconnect-frontend
  labels:
    app: uniconnect-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uniconnect-frontend
  template:
    metadata:
      labels:
        app: uniconnect-frontend
    spec:
      containers:
        - name: frontend
          image:  uniconnectlearninghub/uniconnect-frontend:v1.0.0 # <-- Replace with your image
          ports:
            - containerPort: 5503
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 5503
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5503
            initialDelaySeconds: 30
            periodSeconds: 10
