apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uniconnect-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: www.uniconnect-learninghub.co.ke
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uniconnect-frontend
                port:
                  number: 5503
    - host: app.uniconnect-learninghub.co.ke
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5501
